language: r
cache: packages
r:
  - release

r_check_args: --as-cran

warnings_are_errors: true

sudo: false

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libxml-checker-perl libdbd-pg-perl libperl-critic-perl libdevel-cover-perl

notifications:
  email:
    on_success: change
    on_failure: always

os:
  - linux


r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'

cache: packages
